name: 'Deploy dotNet Pack'

on: 
    push:
        branches:
          - master
        tags: 
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    deploy:
        name: "Deploy"
        runs-on: 'ubuntu-latest'
        steps:
        - name: checkouts
          uses: actions/checkout@v2
        
        - name: Verify commit exists in origin/master
          run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
            git branch --remote --contains | grep origin/master

        - name: Set VERSION variable from tag
          run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

        - name: Build
          run: dotnet build --configuration Release /p:Version=${VERSION}

        - name: Test
          run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

        - name: Pack
          run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .

        - name: Push
          run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/AniYD7651/index.json --api-key ${GITHUB_TOKEN}
          env:
            GITHUB_TOKEN: ${{ secrets.NUGET_AUTH_KEY }}